[tool.commitizen]
name = "cz_customize"
version = "0.2.0"
tag_format = "${version}componentb"
update_changelog_on_bump = true

[tool.commitizen.customize]
changelog_pattern = "^(feat|fix)\\(componentb\\)(!)?:"